/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FarmSettings {
  'yieldRate' : number,
  'activityDuration' : bigint,
  'growthRate' : number,
}
export interface GameConfig {
  'sceneConfig' : string,
  'gravity' : Vector3,
  'ambientLight' : Vector3,
  'farmSettings' : FarmSettings,
}
export interface PersistentFarmData {
  'cropYield' : bigint,
  'lastUpdateTimestamp' : [] | [bigint],
  'cropType' : string,
  'growthRate' : number,
  'farmId' : string,
}
export interface UserProfile { 'farmName' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vector3 { 'x' : number, 'y' : number, 'z' : number }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFarm' : ActorMethod<[string], PersistentFarmData>,
  'getFarms' : ActorMethod<[[] | [string]], Array<PersistentFarmData>>,
  'getGameConfig' : ActorMethod<[], GameConfig>,
  'getPersistentFarmData' : ActorMethod<
    [[] | [string]],
    Array<PersistentFarmData>
  >,
  'getPersistentFarmDataV2' : ActorMethod<
    [[] | [string]],
    Array<PersistentFarmData>
  >,
  'getPersistentGameDataV2' : ActorMethod<[string], [] | [PersistentFarmData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeBackend' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePersistentFarmData' : ActorMethod<
    [string, string, bigint, number],
    undefined
  >,
  'updateFarmData' : ActorMethod<[string, string, bigint, number], undefined>,
  'updateGameConfig' : ActorMethod<[GameConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];