/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'farmName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const PersistentFarmData = IDL.Record({
  'cropYield' : IDL.Nat,
  'lastUpdateTimestamp' : IDL.Opt(IDL.Int),
  'cropType' : IDL.Text,
  'growthRate' : IDL.Float64,
  'farmId' : IDL.Text,
});
export const Vector3 = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const FarmSettings = IDL.Record({
  'yieldRate' : IDL.Float64,
  'activityDuration' : IDL.Nat,
  'growthRate' : IDL.Float64,
});
export const GameConfig = IDL.Record({
  'sceneConfig' : IDL.Text,
  'gravity' : Vector3,
  'ambientLight' : Vector3,
  'farmSettings' : FarmSettings,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFarm' : IDL.Func([IDL.Text], [PersistentFarmData], ['query']),
  'getFarms' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(PersistentFarmData)],
      ['query'],
    ),
  'getGameConfig' : IDL.Func([], [GameConfig], ['query']),
  'getPersistentFarmData' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(PersistentFarmData)],
      ['query'],
    ),
  'getPersistentFarmDataV2' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(PersistentFarmData)],
      ['query'],
    ),
  'getPersistentGameDataV2' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PersistentFarmData)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeBackend' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePersistentFarmData' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'updateFarmData' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'updateGameConfig' : IDL.Func([GameConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'farmName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const PersistentFarmData = IDL.Record({
    'cropYield' : IDL.Nat,
    'lastUpdateTimestamp' : IDL.Opt(IDL.Int),
    'cropType' : IDL.Text,
    'growthRate' : IDL.Float64,
    'farmId' : IDL.Text,
  });
  const Vector3 = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const FarmSettings = IDL.Record({
    'yieldRate' : IDL.Float64,
    'activityDuration' : IDL.Nat,
    'growthRate' : IDL.Float64,
  });
  const GameConfig = IDL.Record({
    'sceneConfig' : IDL.Text,
    'gravity' : Vector3,
    'ambientLight' : Vector3,
    'farmSettings' : FarmSettings,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFarm' : IDL.Func([IDL.Text], [PersistentFarmData], ['query']),
    'getFarms' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(PersistentFarmData)],
        ['query'],
      ),
    'getGameConfig' : IDL.Func([], [GameConfig], ['query']),
    'getPersistentFarmData' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(PersistentFarmData)],
        ['query'],
      ),
    'getPersistentFarmDataV2' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(PersistentFarmData)],
        ['query'],
      ),
    'getPersistentGameDataV2' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PersistentFarmData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeBackend' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePersistentFarmData' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updateFarmData' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updateGameConfig' : IDL.Func([GameConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };